### PR TITLE
Sarah adding title to plot

### PR DESCRIPTION
**Pull request by smerolla**

### CODE REVIEW

**Comment by smerolla** [comment]
@hannahpalmer @maward-sci @mlzulian - anyone want to merge my pull request?

**Comment by maward-sci** [comment]
I merged it! (I think!)

**Comment by maward-sci** [comment]
Looks like when you commit the branch to the master, it tells you you can go ahead and delete the branch that those changes came from.

**Comment by smerolla** [comment]
Yay!

**Pull request merged**
